config/routes.rb
Rails.application.routes.draw do

  resources :contact_messages
  root 'main#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_message.rb
class ContactMessage < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :set_customer, only: [:view_customer]

  def index

    @customers = User.where(role: 'customer')

    @newUser = User.new

    @contact_messages = ContactMessage.all

    @new_demo = Demo.new

    # @projects = Project.all
  end


  def view_customer
    @assign_demo = DemoUsers.new
  end

  private

  def set_customer
    if current_user.role != 'admin'
      @customer = User.find( current_user.id)
    else
      @customer = User.first(0)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_messages_controller.rb
class ContactMessagesController < ApplicationController
  before_action :set_contact_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :except => [:create, :new]


  # GET /contact_messages
  def index
    @contact_messages = ContactMessage.all
  end

  # GET /contact_messages/1
  def show
  end

  # GET /contact_messages/new
  def new
    @contact_message = ContactMessage.new
  end

  # GET /contact_messages/1/edit
  def edit
  end

  # POST /contact_messages
  def create
    @contact_message = ContactMessage.new(contact_message_params)

    ContactMailer.contact_message(@contact_message.name, @contact_message.subject, @contact_message.phone, @contact_message.email, @contact_message.content).deliver_now

    if @contact_message.save
      redirect_to root_url, notice: 'Thanks for the message! For immediate service contact (209) 643-5638.'
    else
      render :new
    end
  end

  # PATCH/PUT /contact_messages/1
  def update
    if @contact_message.update(contact_message_params)
      redirect_to @contact_message, notice: 'Contact message was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /contact_messages/1
  def destroy
    @contact_message.destroy
    redirect_to contact_messages_url, notice: 'Contact message was successfully destroyed.'
  end

  private
  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      session[:admin] = (user_name == 'vas' && password == 'Maxima2017!')
    end
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_message
      @contact_message = ContactMessage.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def contact_message_params
      params.require(:contact_message).permit(:name, :subject, :phone, :email, :content)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def home
    @contact_message = ContactMessage.new

    @login = false
  end
  # Asked for index to be defined so I was going to define it but then altered the routes file for the main controller to look for the home action under the main view subfolder
  # def index
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_messages_helper.rb
module ContactMessagesHelper
end

app/views/admin/index.html.erb
<h1>Admin</h1>
<!--<h2>Create New Customer</h2>-->
<!--<div id="clearance" class="sign-up">-->
      <!--<%#= render partial: '/users/form', object: @newUser %>-->
      <!--<div class="other-links">-->
        <!--<#%= link_to t(".sign_up"), sign_up_url %>-->
      <!--</div>-->
<!--</div>-->
<h2>Customers</h2>
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>Email</th>
    <th>Created-At</th>
    <th>View</th>
    <th>Edit</th>
  </tr>
  </thead>
  <tbody>
  <% @customers.each do |c| %>
      <tr>
        <td><%= c.email %></td>
        <td><%= c.created_at %></td>
        <td>
          <button type="button" class="btn btn-default" data-toggle="modal" data-target="#user_modal_<%= c.id %>">View</button>
        </td>
        <td>
          <%= link_to "Edit", admin_view_customer_path(c), :class => "btn btn-primary" %>
        </td>
      </tr>
  <% end %>
  <!--<tr class="info">-->
  <!--<tr class="success">-->
  <!--<tr class="danger">-->
  <!--<tr class="warning">-->
  <!--<tr class="active">-->
  </tbody>
</table>
<% @customers.each do |c| %>
  <div class="modal fade" id="user_modal_<%= c.id %>" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span class="ion-ios-close-empty"></span>
          </button>
          <span class="pe-7s-volume services-icon-2"></span>
          <h4 class="service-title">Large Modal</h4>
        </div>
        <div class="modal-body">
          <h5 class="heading-1 modal-heading mb20">Customer Info</h5>
          <p>
            <%= c.role %><br>
            <%= c.firstName %>, <%= c.lastName %><br>
            <%= c.company %><br>
            <%= c.phone %><br>
          </p>
          <!--<h5 class="heading-1 modal-heading mb20"></h5>-->
          <!--<p></p>-->
          <!--<h5 class="heading-1 modal-heading mb20">Professionals</h5>-->
          <!--<p class="no-margin-bottom">"</p>-->
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
<% end %>
<hr>

<hr>
<p id="notice"><%= notice %></p>
<hr>

<h1>Contact Messages</h1>

<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>Name</th>
    <th>Subject</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @contact_messages.each do |contact_message| %>
      <tr>
        <td><%= contact_message.name %></td>
        <td><%= contact_message.subject %></td>
        <td><%= contact_message.phone %></td>
        <td><%= contact_message.email %></td>
        <td><%= contact_message.content %></td>
        <td><%= link_to 'Show', contact_message %></td>
        <td><%= link_to 'Edit', edit_contact_message_path(contact_message) %></td>
        <td><%= link_to 'Destroy', contact_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact Message', new_contact_message_path %>

app/views/admin/view_customer.html.erb
<h1>Cuustomer: <%= @customer.email %></h1>
<%= @customer.role %><br>
<%= @customer.firstName %>, <%= @customer.lastName %><br>
<%= @customer.company %><br>
<%= @customer.phone %><br>

<h2>Demo</h2>i
<%= render 'form', demo: @new_customer %>

<%= link_to 'Back', admin_path %> |

app/views/contact_messages/_form.html.erb
<%= simple_form_for @contact_message, remote: true do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :subject %>
    <%= f.input :phone %>
    <%= f.input :email %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contact_messages/edit.html.erb
<h1>Editing Contact Message</h1>

<%= render 'form', contact_message: @contact_message %>

<%= link_to 'Show', @contact_message %> |
<%= link_to 'Back', contact_messages_path %>

app/views/contact_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact Messages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subject</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_messages.each do |contact_message| %>
      <tr>
        <td><%= contact_message.name %></td>
        <td><%= contact_message.subject %></td>
        <td><%= contact_message.phone %></td>
        <td><%= contact_message.email %></td>
        <td><%= contact_message.content %></td>
        <td><%= link_to 'Show', contact_message %></td>
        <td><%= link_to 'Edit', edit_contact_message_path(contact_message) %></td>
        <td><%= link_to 'Destroy', contact_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact Message', new_contact_message_path %>

app/views/contact_messages/new.html.erb
<h1>New Contact Message</h1>

<%= render 'form', contact_message: @contact_message %>

<%= link_to 'Back', contact_messages_path %>

app/views/contact_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact_message.name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @contact_message.subject %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact_message.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_message.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact_message.content %>
</p>

<%= link_to 'Edit', edit_contact_message_path(@contact_message) %> |
<%= link_to 'Back', contact_messages_path %>

app/views/layouts/_header.html.erb
<header>
  <!-- Begin Navigation -->
  <nav class="navbar navbar-logo navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="row">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand scroll-link" href="#home" data-id="home">
            <!--<span class="icon-handle-streamline-vector logo">-->
            <!--<h2>Blue Helmet</h2>-->
            <%= link_to image_tag("logo_black.png", class: "logo1 topReveal", alt: 'Logo'), root_path %>
            <!--</span>-->
          </a>
        </div>

        <% if current_page?(root_url) %>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="#home" data-id="home" class="scroll-link">Home</a></li>
                <li><a href="#ideology" data-id="ideology" class="scroll-link">Ideology</a></li>
                <li><a href="#services" data-id="services" class="scroll-link">Services</a></li>
                <li><a href="#packages" data-id="packages" class="scroll-link">Packages</a></li>
                <li><a href="#contact" data-id="contact" class="scroll-link">Contact</a></li>
              </ul>
            </div><!-- /.navbar-collapse -->
        <% else %>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="<%= root_url %>">Home</a></li>
              </ul>
            </div><!-- /.navbar-collapse -->
        <% end %>
      </div>
    </div><!-- /.container-fluid -->
  </nav>
  <!-- End Navigation -->
</header>
<!-- End Header -->

app/views/layouts/_navbar.html.erb
<% if signed_in? %>
    <% if current_user.role == 'admin' %>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Blue Helmet", root_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <ul class="nav navbar-nav">
            <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</a></li>-->
            <li><%= link_to "All Projects", admin_path %> </li>
            <li><%= link_to "New Project", root_path %> </li>
            <li><%= link_to "Logout", root_path %> </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Blue Helmet</a></li>
          </ul>
        </div>
      </div>
    </nav>
  <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
	<%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
	%>
	<meta charset="utf-8"/>
	<meta name="author" content="Vasilis Kaloidis"/>
	<meta name="description" content="Blue Helmet Software">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<title>Blue Helmet Software Company</title>
	
	<!-- Devicon Icons -->
	<link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
	
	<!-- Royal Preloader CSS -->
	<%= stylesheet_link_tag "royal_preloader" %>
	
	<!-- jQuery Files -->
	<!-- <script type="text/javascript" src="httdp://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->
	<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" %>
	
	<!-- Parallax File -->
	<%= javascript_include_tag "parallax.min.js" %>
	<%#= javascript_include_tag "drift.js" %>
	
	
	<!-- Royal Preloader -->
	<%= javascript_include_tag "royal_preloader.min.js" %>
	
	<script type="text/javascript">
		Royal_Preloader.config({
			mode: 'number',
			showProgress: false,
			background: '#1d1d1d'
		});
	</script>
	
	<!-- Stylesheets -->
	<%= stylesheet_link_tag "bootstrap.css" %>
	<%= stylesheet_link_tag "ionicons.css" %>
	<%= stylesheet_link_tag "pe-icon-7-stroke.css" %>
	<%= stylesheet_link_tag "magnific-popup.css" %>
	<%= stylesheet_link_tag "logoiconfont.css" %>
	<%= stylesheet_link_tag "style.css" %>
	<%= stylesheet_link_tag "colors/blue.css" %>
	<%#= stylesheet_link_tag "base-light.css" %>
	
	<% login = false %>
	
	<!--<link type="text/css" href="css/colors/blue.css" />-->
	<!--<link type="text/css" href="base-light.css" />-->
	<!--<link rel="alternate .cssstylesheet" type="text/css" href="css/colors/green.css" title="green">-->
	<!--<link rel="alternate stylesheet" type="text/css" href="css/colors/orange.css" title="orange">-->
	<!--<link rel="alternate stylesheet" type="text/css" href="css/colors/red.css" title="red">-->
	<!--<link rel="alternate stylesheet" type="text/css" href="css/colors/orangelight.css" title="orangelight">-->
	<!--<link rel="alternate stylesheet" type="text/css" href="css/colors/pinkish.css" title="pinkish">-->
	<!--<link rel="alternate stylesheet" type="text/css" href="css/colors/seagul.css" title="seagul">-->
	<title><%#= title %>Blue Helmet Software</title>
	<%= stylesheet_link_tag :application, media: "all" %>
	
	<%= csrf_meta_tags %>

  <!-- Start of Async Drift Code -->
  <script>
      !function() {
          var t;
          if (t = window.driftt = window.drift = window.driftt || [], !t.init) return t.invoked ? void (window.console && console.error && console.error("Drift snippet included twice.")) : (t.invoked = !0,
              t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ],
              t.factory = function(e) {
                  return function() {
                      var n;
                      return n = Array.prototype.slice.call(arguments), n.unshift(e), t.push(n), t;
                  };
              }, t.methods.forEach(function(e) {
              t[e] = t.factory(e);
          }), t.load = function(t) {
              var e, n, o, i;
              e = 3e5, i = Math.ceil(new Date() / e) * e, o = document.createElement("script"),
                  o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + i + "/" + t + ".js",
                  n = document.getElementsByTagName("script")[0], n.parentNode.insertBefore(o, n);
          });
      }();
      drift.SNIPPET_VERSION = '0.3.1';
      drift.load('di4et8rgkcup');
  </script>
  <!-- End of Async Drift Code -->

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-36624287-2"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-36624287-2');
  </script>



</head>

<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, class: "alert alert-success" %>
<% end %>

<body class="royal_preloader" data-spy="scroll" data-target=".navbar" data-offset="70">

<div id="royal_preloader"></div>

<%= render 'layouts/header' %>

<%#= render 'layouts/navbar' %>

<%= yield %>

<!-- Begin Footer -->
<footer class="footer-padding background2">
	<div class="container">
		<div class="row no-margin-bottom">
			<div class="text-center no-margin-bottom">
				<button type="button" class="btn btn-primary btn-up-footer btn-lg scroll-top">Up</button>
			</div>
		</div>
		<div class="row">
			<div class="text-small text-center">
				<hr>
				<div class="row">
					<p class="no-margin">&copy; Blue Helmet Software Company</p>
					<!--<a href="<%#= sign_out_path %>" type="button" class="btn btn-primary btn-up-footer btn-lg">Logout</a>-->
				</div>
			</div><!-- /.column -->
		</div><!-- /.row -->
	</div><!-- /.container -->
</footer><!-- /.footer -->
<!-- Begin Footer -->

<!-- Javascript Files -->
<%= javascript_include_tag "bootstrap.min.js" %>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyArLNT3t4qsJEBmR0R9P_6ueLIQz0Jvt1M&callback=initMap" async defer></script>
<%= javascript_include_tag "google_maps_stock.js" %>
<%= javascript_include_tag "particles.min.js" %>
<%= javascript_include_tag "particlesRun" %>
<%= javascript_include_tag "jquery.mixitup.js" %>
<%= javascript_include_tag "form-validator.min.js" %>
<%= javascript_include_tag "jquery.inview.min.js" %>
<%= javascript_include_tag "jquery.countTo.js" %>
<script type="text/javascript">
	/* ---- Counter (our count) ---- */
	$('#ourcount').one('inview', function (event, isInView) {
		if(isInView) {
			$('.timer').countTo({speed: 3000});
		}
	});
</script>

<%= javascript_include_tag "jquery.magnific-popup.min.js" %>
<%= javascript_include_tag "scrollreveal.min.js" %>
<%= javascript_include_tag "main.js" %>

</body>

</html>

app/views/main/_about.html.erb
<section id="about" class="background1 section-padding">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 section-title text-center">
        <h2>About</h2>
        <span class="section-divider"></span>
      </div><!-- /.column -->
    </div><!-- /.row -->
    <div class="row mb15">
      <div class="col-sm-5 leftReveal">
        <h5 class="heading-1 mb20">Our Trade</h5>
        <h3 class="mb15 no-margin-top">We love writing code <br>And we are really really good at it...</h3>
        <p class="no-margin text-small">Code is our thing. It's what we do best, and we enjoy doing it. We take pride in what we do, and personally garuntee
          you will receive a product that you absolutley love, or you don't pay for it. Simple. We do this because we take pride in what we do, we are good
          at it, and we'll give you a great product!</p>
      </div><!-- /.column -->
      <div class="col-sm-7 mt30-xs rightReveal">
        <h5 class="heading-1 mb20">How we started it</h5>
        <span class="icon-handle-streamline-vector logo-about"></span>
        <p>We started by just writing code. Lots of it. We love writing code, and still do. We do it all day every day.</p>
      </div><!-- /.column -->
    </div><!-- /.row -->
    <div class="row mb30">
      <div class="col-sm-9 leftReveal">
        <h5 class="heading-1 mb20">The Skinny -</h5>
        <p class="lead no-margin">
          Well give you a better product than anybdoy else,
          before you even pay us, and show it to you before you pay, to make sure you love it.
          We want you to love it. And we put our money where our mouth is. We have little overhead,
          so don't pay any other big design / marketing firm TONS of money, when we can give you a better
          product for a quarter of the cost.
        </p>
      </div><!-- /.column -->
    </div><!-- /.row -- -->
  </div><!-- /.container -->
</section><!-- /.section -->

app/views/main/_brandIcons.html.erb
<section id="technologies" class="section-padding parallax-window" data-parallax="scroll" data-image-src="<%= image_url('small-slider2.jpg') %>">
	<div class="container">
		<ul class="clients-grid grid-6 nobottommargin clearfix">
			<li><i class="devicon-amazonwebservices-plain-wordmark colored"></i></li>
			<li><a href="http://logofury.com"><img src="images/clients/2.png" alt="Clients"></a></li>
			<li><a href="http://logofaves.com/2014/03/grabbt/"><img src="images/clients/3.png" alt="Clients"></a></li>
			<li><a href="http://logofaves.com/2014/01/ladera-granola/"><img src="images/clients/4.png" alt="Clients"></a></li>
			<li><a href="http://logofaves.com/2014/02/hershel-farms/"><img src="images/clients/5.png" alt="Clients"></a></li>
			<li><a href="http://logofury.com/logo/food-fight-radio.html"><img src="images/clients/6.png" alt="Clients"></a></li>
			<li><a href="http://logofury.com"><img src="images/clients/7.png" alt="Clients"></a></li>
			<li><a href="http://logofury.com/logo/up-travel.html"><img src="images/clients/8.png" alt="Clients"></a></li>
			<li><a href="http://logofury.com/logo/caffi-bardi.html"><img src="images/clients/9.png" alt="Clients"></a></li>
			<li><a href="http://logofury.com/logo/bignix-design.html"><img src="images/clients/10.png" alt="Clients"></a></li>
			<li><a href="http://logofury.com/"><img src="images/clients/11.png" alt="Clients"></a></li>
			<li><a href="http://logofury.com/"><img src="images/clients/12.png" alt="Clients"></a></li>
		</ul>
	</div><!-- /.container -->
</section><!-- /.section -->

app/views/main/_carousel.html.erb
<section class="background1" id="ideology">
	<div id="our-process-title" class="pt30 pb30">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<h4 class="no-margin">About Us</h4>
				</div>
			</div>
		</div>
	</div>
	<!-- Begin Quote Carousel -->
	<div id="carousel" class="testimonial-carousel pt40 pb20 section-padding-top">
		<div class="container">
			<div class="row">
				<div class="col-md-10 col-md-offset-1 text-center">
					<span class="pe-7s-close heading-3-icon"></span>
					<div class="fade-quote-carousel carousel slide" id="quote-carousel" data-ride="carousel" data-interval="3000">
						<!-- Carousel indicators -->
						<ol class="carousel-indicators">
							<li data-target="#quote-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#quote-carousel" data-slide-to="1"></li>
							<li data-target="#quote-carousel" data-slide-to="2"></li>
						</ol>
						<!-- Carousel items -->
						<div class="carousel-inner">
							<div class="active item">
								<blockquote>
									<p>Talented Software Engineers, seasoned veterans in the software industry</p>
								</blockquote>
							</div>
							<div class="item">
								<blockquote>
									<p>Social-Media Experts, who can grow your followers and popularity.</p>
								</blockquote>
							</div>
							<div class="item">
								<blockquote>
									<p>Web Developers, who keep up on the latest web trends and technologies. </p>
								</blockquote>
							</div>
						</div>
					
					</div><!-- /.carousel -->
				</div><!-- /.column -->
			</div><!-- /.row -->
		</div><!-- /.container -->
	</div><!-- /.carousel -->
	<!-- End Quote Carousel -->
</section>

app/views/main/_contact.html.erb
<section id="contact" class="background2 section-padding">
  <div class="container">
    <div class="row mb30">
      <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 section-title text-center">
        <h2>Contact</h2>
        <span class="section-divider mb15"></span>
        <p class="no-margin scaleReveal">Contact us using the contact form below </p>
	      <p class="no-margin scaleReveal">Ready to grab a coffee? Call or text us at (209) 643-5638 to discuss your next project</p>

      </div><!-- /.column -->
    </div><!-- /.row -->
    <div class="row">
      <div class="col-sm-5 col-lg-4">
        <h5 class="heading-1 mb20">Visit Us</h5>
        <h4 class="mb15">Woodbury, CT</h4>
	      <h5 class="heading-1 mb20">Contact Us</h5>
        <p class="text-xs-small mb5"><strong class="text-switch">Email:</strong> blue.helmet.dev@gmail.com</p>
        <p class="text-xs-small mb5"><strong class="text-switch">Phone:</strong> +1 (209) 643-5638</p>
      </div><!-- /.column -->
      <div class="col-sm-6 col-lg-7 mt30-xs">
        <%= render 'main/messageForm' %>
      </div><!-- /.column -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</section><!-- /.section -->

app/views/main/_hello.html.erb
<!-- Begin Hello Intro -->
<div id="hello-intro" class="pt60 pb60">
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-sm-3">
        <h2 class="no-margin rotateLeftReveal">Hello.</h2>
      </div>
      <div class="col-lg-10 col-sm-9 mt30-xs">
        <h3 class="no-margin rightReveal">We are a team of Software Engineers, Web Developers and
          Brand / Marketing Guru's <strong>ready to parse your Dreams, and compile them into Code</strong></h3>
      </div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</div><!-- /.div -->
<!-- End Hello Intro -->

app/views/main/_jumbotron.html.erb
<!-- Begin Jumbotron -->
<div class="jumbotron jumbotron-main" id="home">
  <div id="particles-js"></div><!-- /.particles div -->
  <div class="container center-vertically-holder">
    <div class="center-vertically">
      <div id="scaleReveal" class="col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3 text-center">
        <!--<span class="icon-handle-streamline-vector big-logo"></span>-->
        <div class="ticker">
          <h1>Software</h1>
          <h1>Web</h1>
          <h1>Social</h1>
        </div>
        <hr>
        <p>
          Software development, media and marketing
        </p>
        <a href="#services" data-id="services" class="scroll-link btn btn-default btn-white btn-lg mt15">Services
          <span class="ion-android-arrow-down"></span></a>
      </div><!-- /.column -->
    </div><!-- /.vertical center -->
  </div><!-- /.container -->
</div>
<!-- End Jumbotron -->